Repository coding-geek21/classDeck, pull requests merged in 2022-03, with the labels that each got.

#32 Enhanced teacher dashboard.
  classDeck/classroom/templates/classroom/teachers/teacher_home.html
Labels: GSSoC22, Level2

#33 Add Code_Of_Conduct.md
  Code_Of_Conduct.md
Labels: GSSoC22, Level1

#35 Prateek
  .gitignore
  README.md
  classDeck/classDeck/.env_template
  classDeck/classDeck/settings.py
  classDeck/classDeck/urls.py
  classDeck/classroom/forms.py
  classDeck/classroom/urls.py
  classDeck/classroom/utils.py
  classDeck/classroom/views/classroom.py
  classDeck/classroom/views/students.py
  classDeck/classroom/views/teachers.py
  classDeck/templates/registration/signup_form.html
Labels: GSSoC22, Level3, Changes requested

#55 Footer enhance
  classDeck/templates/base.html
Labels: GSSoC22, Level1

#58 Issue #46 Forgot password feature
  classDeck/classDeck/urls.py
  classDeck/classroom/templates/reset_password/password_reset.html
  classDeck/classroom/templates/reset_password/password_reset_complete.html
  classDeck/classroom/templates/reset_password/password_reset_confirm.html
  classDeck/classroom/templates/reset_password/password_reset_email.html
  classDeck/classroom/templates/reset_password/password_reset_subject.txt
  classDeck/classroom/views/reset_password.py
  classDeck/templates/registration/login.html
Labels: GSSoC22, Level3, Changes requested

#62 Changes in Readme
  README.md
Labels: GSSoC22, Level1

#64 Updated Readme
  README.md
Labels: GSSoC22, Level1

#57 Final issue#25
  classDeck/classroom/templates/classroom/home.html
  classDeck/templates/base.html
Labels: GSSoC22, Level1

#37 First
  classDeck/classroom/templates/classroom/home.html
  classDeck/classroom/templates/classroom/teachers/question_add_form.html
  classDeck/classroom/templates/classroom/teachers/question_change_form.html
  classDeck/classroom/templates/classroom/teachers/question_delete_confirm.html
  classDeck/classroom/templates/classroom/teachers/quiz_add_form.html
  classDeck/classroom/templates/classroom/teachers/quiz_change_form.html
  classDeck/classroom/templates/classroom/teachers/quiz_change_list.html
  classDeck/classroom/templates/classroom/teachers/quiz_delete_confirm.html
  classDeck/classroom/templates/classroom/teachers/quiz_results.html
  classDeck/static/img/add_question.svg
  classDeck/static/img/delete.svg
  classDeck/static/img/quiz2.svg
  classDeck/static/img/quiz3.svg
  classDeck/static/img/result.svg
  classDeck/templates/base.html
Labels: GSSoC22, Level3

#67 contact us template
  classDeck/templates/contactus.html
Labels: GSSoC22, Level2
